### ISSUE TITLE
exact match for target SDK version: 1.2.1 using device: square_watch

### ISSUE THREAD

**Issue by mirkos-vf** [liias/monkey#4] opened 2016-11-20 05:55 UTC
Hello. I am getting an issue where the trying to run the app on a simulator says "Error:Unable to find exact match for target SDK version: 1.2.1 using device: square_watch"

My SDK is 2.2.1. I tried adding -s 2.2.1 as an argument in the configuration section but that had no effect on the actual deploy script.

**Comment by liias** [comment] 2016-11-20 22:14
The SDK version has to be in two places:
1) In Project Structure "Target SDK version". This will add -s flag during compiling
2) In manifest.xml the minSdkVersion attribute

Also target device matters. Currently target device is configured in:
1) In Project Structure "Target Device". This will add -d flag (currently always with _sim suffix)
2) In Run Configuration "Target Device". This will append device name to the monkeydo command
3) In manifest.xml device should be in

Try to "Rebuild Project" after doing changes and then run the app.

**Comment by mirkos-vf** [comment] 2016-11-24 07:51
I tried to do everything as you wrote, the problem remained and also appeared new.
Unable to setup SDK with ConnectIQ 2.1.5

**Comment by liias** [comment] 2016-11-24 18:00
Could you specify what version is set in these two places and what device in the three places? I could try to reproduce.

**Comment by Berstad** [comment] 2017-02-06 16:59
I am also experiencing this issue. Installed SDK is version 2.2.4. There is no way to set this version in project structure (it only allows 1.2.x, 1.3.x and 2.1.x).  Could you make it so that it is possible to specify the SDK version explicitly or add 2.2.x?

Device is set as square_watch in all three places and minSdkVersion is 2.2.4.

**Comment by yulrizka** [comment] 2017-02-11 13:55
For me it works if i change the <project>.iml 
   
    target-sdk-version="2.2.4"

**Comment by Berstad** [comment] 2017-02-11 14:07
Thanks @yulrizka, that did the trick!

**Comment by liias** [comment] 2017-02-22 19:16
Hey, thanks for reporting it.
Since SDK 2.2.2 garmin devs added these versions to compilerInfo (instead of hardcording to eclipse plugin), so this plugin will also use it now. I will close the issue.

PS! Make sure you use correct device - sdk version pair (you could open your project in the eclipse plugin to see what options are available), I haven't updated that usability (and probably won't anytime soon).

**Closed by liias** 2017-02-22 19:16 UTC
